name: Send Notifications

on:
  schedule:
    # Every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: worker/package.json
    
    - name: Install dependencies
      working-directory: ./worker
      run: npm ci
    
    - name: Run worker
      working-directory: ./worker
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
      run: node worker.js